version: "3.9"

services:
  backend:
    build: .
    container_name: warrantrix-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/warrantrix
      - JWT_SECRET_KEY=devsecret
      - JWT_ALGORITHM=HS256
      - APP_NAME=Warranty Intelligence Copilot
      - ENV=dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: warrantrix-db
    environment:
      - POSTGRES_DB=warrantrix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
